In [9]:
#!pip install tensorboardX
#!pip install jupyter-tensorboard
# !pip install tensorflow
# !pip install keras
# !pip install h5py
# !python3 -m pip install --upgrade tensorflow

In [7]:
#1.임포트 
import tensorflow as tf

In [23]:
#2. 행과 열을 만들자
matrix1 = tf.constant([[3,3] ])
matrix1

matrix2 = tf.constant([[2],[2] ])
matrix2

res = tf.matmul(matrix1, matrix2)
print(res)
#tf.constant([1, 2, 3, 4, 5, 6])

x = tf.constant([1, 2, 3, 4])
res02= tf.multiply(x,x)
print(res02)

hap = tf.add(x,x)
print(hap)

tf.Tensor([[12]], shape=(1, 1), dtype=int32)
tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int32)
tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)


In [28]:
#행렬 연산을 구현해보자 
input01 = tf.constant([3.0])
input02 = tf.constant([2.0])
input03 = tf.constant([5.0])

hap = tf.add(input02, input03)
res = tf.multiply(input01, hap)
print(hap)
print(res)

#중첩가능한지 확인
res02 = tf.multiply(input01, tf.add(input02, input03))
print(res02)


tf.Tensor([7.], shape=(1,), dtype=float32)
tf.Tensor([21.], shape=(1,), dtype=float32)
tf.Tensor([21.], shape=(1,), dtype=float32)


In [32]:
#3.즉시 기본 실행
tf.executing_eagerly()
x =[[2]]
m = tf.multiply(x,x)
print(f'hello{m}')
print('hello,{}'.format(m))

hello[[4]]
hello,[[4]]


In [39]:
#4. 반환작업
a = tf.constant([[1,2],[3,4]])
print(a)
print(a.shape)
print(a.dtype, type(a.dtype))
print(a.numpy().dtype, type(a.numpy()))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
(2, 2)
<dtype: 'int32'> <class 'tensorflow.python.framework.dtypes.DType'>
int32 <class 'numpy.ndarray'>


In [41]:
#5. 브로드케스팅 (Broadcasting) 지원
b = tf.add(a,1)
print(b)

#6. 연산자 오버로딩
print(a*b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [43]:
# Numpy 지원
import numpy as np
res = np.multiply(a,b)
print(res , type(res))

[[ 2  6]
 [12 20]] <class 'numpy.ndarray'>


In [51]:
# Variable
name = tf.Variable("홍길동", tf.string)
kor = tf.Variable(100, tf.int32)
eng = tf.Variable(90, tf.int32)
tot = kor + eng
print(name.numpy())
print(tot.numpy())
name02 = tf.Variable(["홍길동"], tf.string)
name02.numpy()

b'\xed\x99\x8d\xea\xb8\xb8\xeb\x8f\x99'
190


array([b'\xed\x99\x8d\xea\xb8\xb8\xeb\x8f\x99'], dtype=object)

In [61]:
a = tf.Variable([3,12345,2.3295], tf.float32)
b = tf.Variable([1,2,3,4,5],tf.int32)
c = tf.Variable([12.3-4.85j, 7.5-6.12j], tf.complex64)
a,b,c
a.numpy(), b.numpy(), c.numpy()
a.numpy()[1]

12345.0

In [64]:
# tensor 차원을 리턴 받자 tf.zeros(), tf.rank()
# 배치 *높이 * 너비 *색상
my_img = tf.zeros([10,299,299,3])
res = tf.rank(my_img)
res

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [66]:
# 요소를 리턴
my_v = tf.Variable([1,2,3,4])
my_s = my_v[2]
print(my_s.numpy())

3


In [67]:
# tf의 객체를 Variable로 연동해보자 
my_val = tf.Variable(tf.zeros([2,2,3])) #상수
my_val.numpy()

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [ ]:
# tf의 객체를 Variable로 연동해보자 
my_val = tf.constant(tf.zeros([2,2,3])) #변수
my_val.numpy()

In [75]:
# 변수 자동변환
v = tf.Variable(0.0)
v.numpy()

w = v+1 
w

v = tf.Variable(0.0)
v.assign_add(1)
print(v.read_value())
print(v)

tf.Tensor(1.0, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [114]:
#3*2행의 float32값을 이용해서 값을 구현해보자
a = tf.Variable([[1,2],[3,4],[5,6]], dtype = tf.float32)
print(a.numpy())

#전체 -값으로 변경해보자
a.assign([[-1,-2],[-3,-4],[-5,-6]])
print(a.numpy())

#3*2행의 값을 모두 0으로 초기화 float32
b = tf.Variable(tf.zeros([3,2]), dtype = tf.float32)
print(a.numpy())

#3*2의 행의 값을 요소모두의 평균은 0, 표준편차 0.1의 정규 난수로 초기화를 시켜봐라
#tf.random_normal_initializer(mean=0.0, stddev=0.05, seed=None)
#tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None)
a = tf.Variable(tf.random.normal([3,2], mean=0.0, stddev=0.1, dtype = tf.dtypes.float32))
print(a.numpy())

#3*2의 행의 값을 요소모두를 -1~3까지의 범위의 균일 값을 난수로 초기화 시켜라
a = tf.Variable(tf.random.normal([3,2], mean=1, stddev=3, dtype = tf.dtypes.float32))
print(a.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[-1. -2.]
 [-3. -4.]
 [-5. -6.]]
[[-1. -2.]
 [-3. -4.]
 [-5. -6.]]
[[ 0.13852419  0.17976241]
 [ 0.13863638  0.19217838]
 [-0.15452793  0.04327468]]
[[-0.56239986  2.5044527 ]
 [-0.47417617 -2.337158  ]
 [ 4.6500998   3.9490402 ]]


In [121]:
# f(x) 표현하는 연산 시스템
# log(x), exp(x), sin(x), cos(x), sigmoid(x), tanh(x)등

a = tf.constant([1,2,3], tf.float32)
b = tf.math.log(a)
print(b.numpy())

b = tf.math.tanh(a)
print(b.numpy())

b = tf.math.sigmoid(a)
print(b.numpy())


b = tf.math.sin(a)
print(b.numpy())

[0.        0.6931472 1.0986123]
[0.7615942 0.9640276 0.9950547]
[0.7310586  0.8807971  0.95257413]
[0.84147096 0.9092974  0.14112   ]


softmax : 로지스틱함수를 다차원으로 만든것

다항 로지스틱 회귀로 출력에 대한 확률분포로 네트워크 출력을 하는 정규화 

신경망의 활성화 홤수로 자주 사용된다. (one-hot)

z = K로 실수값을 벡터를 받아서 입력숫자에 지수에 비례하는 K개의 확률 분포를 정규화 시킨것

    tf.nn.softmax(logits, axis=None, name=None)
    softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)

    tf.nn.softmax(x)
    입력 인수 x : 텐서, 정수 상수 텐서, 변수 상수
    출력 값
        1. x의 각 요소마다 exp()을 계산에서 A에 할당
        2. A의 요소를 모두 더해서 임의변수 a에 넣는다.
        3. A의 요소를 a로 나누어서 출력 텐서를 한다.
        4. 출력 텐서의 각 요소의 값은 확률을 나타낸다.

In [124]:
A = tf.constant([1,2,3],tf.float32)
B = tf.nn.softmax(A)
print(B.numpy()) #확률 분포

B = tf.reduce_sum(A)
print(B.numpy())

[0.09003057 0.24472848 0.66524094]
6.0


In [129]:
#사용자 오퍼레이션 만드는법 
'''
    @tf.funtion
    def 함수명():
        연산
        return
'''

#(a+b)*c mpOP(a,b,c)
@tf.function
def myOP(a,b,c):
    t = tf.math.add(a,b)
    return tf.math.multiply(t,c)

A = tf.constant([1,2], tf.float32)

B = tf.constant([3,4], tf.float32)

C = tf.constant([5,6], tf.float32)

d = myOP(a,b,c)
print(d, type(d))
print(d.numpy())

tf.Tensor([20. 36.], shape=(2,), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>
[20. 36.]


In [133]:
# 사용자 자료형 만들기
# tf.Module를 상속받아구현한다
# tf.Module 인스턴스는 Variable을 포함해서 다른 모듈들을 탐색할 수 있다. 
# trainable_variables = 훈련가능한 변수를 리턴

class MyModuleOne(tf.Module):
    def __init__(self):
        self.V0 = tf.Variable(1.0)
        self.Vs = [tf.Variable(x) for x in range(10)]
class MyOtherModule(tf.Module):
    def __init__(self):
        self.m = MyModuleOne()
        self.v = tf.Variable(10.0)
        
m = MyOtherModule()
len(m.variables)
print(m.variables)
print(m.m)
print(m.v)

(<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>, <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>)
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>


In [135]:
#케라스
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

In [148]:
# 순차모델을 만들어보자

model = tf.keras.Sequential([
    tf.keras.layers.Dense(100, name = 'Layer_0', input_shape = (1000,)),
    tf.keras.layers.Dense(10, name = 'Layer_1'),
    tf.keras.layers.Dense(1, name = 'Layer_2'),
])

#model.summary()
print(type(model.layers[0]))
print(model.layers[0].name)



d = {k.name : i for i, k in enumerate(model.layers)}
print(d)
print(d['Layer_1'])
print(d.get('Layer_1'))

layer_name = [k.name for k in model.layers]
print(layer_name)

<class 'tensorflow.python.keras.layers.core.Dense'>
Layer_0
{'Layer_0': 0, 'Layer_1': 1, 'Layer_2': 2}
1
1
['Layer_0', 'Layer_1', 'Layer_2']


심층 신경망은 학습한 모든 변환을 수치 데이터 텐서 연산을 사용한다.
ex)텐서 덧셈, 텐서 곱셈

tf.keras.layers.Dense(1, name='Layer_2') -> 신경망을 만들었다. 층을 설정했다.

    데이터 -> 학습구조모델링 -> 학습 수행 -> 평가

In [153]:
# 간단한 공식을 이용해서 값을 전달한 후 평가로 예측 값을 구현해보자

#데이터
# y =ax +b
x = np.array([1,2,3,4,5])
y = x*2+1
print(x)
print(y)


# 학습구조 모델링
model = tf.keras.Sequential() #레이어를 층층히 쌓아주는 메소드
model.add(layers.Dense(1, input_shape=(1,)))

model.compile('SGD','mse')

#SGD (Stochastic gradient descent : 확률적 경사 하강법)
# mse(Mean Squared Error: 평균 제곱 오차)

# 학습수행 
model.fit(x,y, epochs=10000, verbose=0)

#평가
print('y:',y,'predict:',model.predict(x).flatten())


[1 2 3 4 5]
[ 3  5  7  9 11]
y: [ 3  5  7  9 11] predict: [ 2.9999883  4.9999933  6.9999986  9.000004  11.000009 ]


In [155]:
# tf.GradientTape API : 텐서플로는 자동 미분하는 API를 제공한다.
# context 안에 실행된 모든 연산을 tape에 기록한다.
# 후진방식 자동미분을 사용해서 tape에 기록된 연산을 결과를 계산한다.

x = tf.ones((2,2))

with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)
    
dz_dx = t.gradient(z,x)
for i in [0,1]:
    for j in [0,1]:
        dz_dx[i][j].numpy() == 8.0
        print(dz_dx[i][j])

tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
