In [8]:
# Shapes of Dense Layers
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 32000, 10
x = tf.random.normal(shape=(N, n_feature))
print(x.shape)

dense = Dense(units=1, activation='relu') # imp. an AN
y = dense(x) # forward propagation
W, B = dense.get_weights()
print(y.shape)
print(W.shape, B.shape)


(32000, 10)
(32000, 1)
(10, 1) (1,)


In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature))

dense = Dense(units=1, activation='sigmoid') # imp. an AN
y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B
y_man = 1/(1 + tf.math.exp(-y_man)) # sigmoid

print(y_tf.numpy())
print(y_man.numpy())

[[0.7302997 ]
 [0.7073016 ]
 [0.85964644]
 [0.54993886]
 [0.4499604 ]
 [0.38135242]
 [0.15301937]
 [0.5333911 ]]
[[0.7302997 ]
 [0.70730156]
 [0.85964644]
 [0.54993886]
 [0.44996038]
 [0.38135242]
 [0.1530194 ]
 [0.5333911 ]]


In [14]:
import tensorflow as tf
import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense


N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3 
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print('======= Input/Weight/Bias ========')
print(f"X: {X.shape}")
print(f"W: {W.shape}")
print(f"B: {B.shape}")
print("Y(Tensroflow): \n", Y_tf.numpy())

# calculate with matrix multiplication
z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-z))
print("Y(with matrix multiplication): \n", Y_man_matmul.numpy())

# calculate with dot products
Y_man_vce = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]
    
    for nu_idx in range(n_neuron):
        w, b =W[:, nu_idx], B[nu_idx]
        
        z = tf.reduce_sum(x * w) + b
        a = 1/(1 + np.exp(-z))
        Y_man_vce[x_idx, nu_idx] = a

print("Y(with dot products): \n",Y_man_matmul.numpy())
        

======= Input/Weight/Bias ========
X: (4, 10)
W: (10, 3)
B: (3,)
Y(Tensroflow): 
 [[0.58192617 0.5135863  0.32401222]
 [0.71702886 0.7770231  0.7349999 ]
 [0.7377607  0.53462285 0.6777708 ]
 [0.60145503 0.6483003  0.2066369 ]]
Y(with matrix multiplication): 
 [[0.58192617 0.5135863  0.32401222]
 [0.71702886 0.77702296 0.7349999 ]
 [0.7377607  0.53462285 0.6777708 ]
 [0.60145503 0.6483003  0.20663689]]
Y(with dot products): 
 [[0.58192617 0.5135863  0.32401222]
 [0.71702886 0.77702296 0.7349999 ]
 [0.7377607  0.53462285 0.6777708 ]
 [0.60145503 0.6483003  0.20663689]]


In [25]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense_1 = Dense(units=n_neurons[0], activation='sigmoid')
dense_2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense_1(X)
Y = dense_2(A1)

# get weight/bias
W1, B1 = dense_1.get_weights()
W2, B2 = dense_2.get_weights()


print(f"X: {X.shape} \n")

print(f"W1: {W1.shape}")
print(f"B1: {B1.shape}")
print(f"A1: {A1.shape} \n")

print(f"W2: {W2.shape}")
print(f"B2: {B2.shape}")
print(f"Y: {Y.shape}")


X: (4, 10) 

W1: (10, 3)
B1: (3,)
A1: (4, 3) 

W2: (3, 5)
B2: (5,)
Y: (4, 5)


In [38]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [32, 64, 128, 128, 256]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

print(dense_layers[0])

print(f"Input: {X.shape}")
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer", dense_idx+1)
    print(X.shape, '\n')
Y = X
print(Y)

Input: (4, 10)
After dense layer 1
(4, 32) 

After dense layer 2
(4, 64) 

After dense layer 3
(4, 128) 

After dense layer 4
(4, 128) 

After dense layer 5
(4, 256) 

tf.Tensor(
[[0.         0.         0.         ... 0.05131515 0.         0.17010298]
 [0.0294273  0.0584216  0.05767941 ... 0.15291649 0.         0.23191777]
 [0.         0.05763807 0.         ... 0.         0.         0.0360278 ]
 [0.         0.         0.00379588 ... 0.0413337  0.         0.18325104]], shape=(4, 256), dtype=float32)


In [40]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense


N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [32, 64, 128, 128, 256]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

print(dense_layers[0])

print(f"Input: {X.shape}")
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)
    print("After dense layer", dense_idx+1)
    print(X.numpy(), '\n')


Input: (4, 10)
After dense layer 1
[[0.         0.51465964 0.         0.         0.10108626 0.33711523
  1.620247   0.         0.         0.         0.         0.79865545
  0.         0.63613033 0.         0.         0.41912276 1.5150144
  0.         0.44937328 0.         0.24299023 0.         0.83869565
  0.         0.         0.43525353 0.         0.         0.0545099
  0.6125084  1.2827876 ]
 [0.6152668  0.         0.         0.         0.         0.
  0.7746406  0.         0.         0.         0.19521458 0.
  0.         0.         0.         0.5769544  0.7520638  0.11289363
  0.60415393 0.         0.         0.25246373 0.         1.2033076
  0.5914184  0.7586682  0.770066   0.61019045 0.06808569 0.39303195
  0.7691959  1.4437518 ]
 [0.         0.73408175 0.         0.41611052 0.2165849  0.
  0.24580027 0.2953407  0.         0.         0.         0.
  0.9008979  0.         0.         0.06697388 0.26241672 0.289085
  0.         0.22679357 0.         0.         0.         0.10916606
